channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - plotly
  - pip:
    - xmltodict
    - requests
    - joblib
    - tqdm
    - networkx
    - pyteomics
    - pyyaml
    - kaleido