channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - pandas
  - matplotlib
  - pip:
    - xmltodict
    - requests
    - joblib
    - tqdm
    - networkx
    - pyteomics
    - pyyaml